service: bulk-sms

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: aws-apikey-dev
  memorySize: 128
  timeout: 300
  region: ap-southeast-2

package:
  include:
    - node_modules/*

functions:
  main:
    handler: handler.main
    environment:
      accountSid: ${ssm:bulksms-accountSid~true} #account sid
      authToken: ${ssm:bulksms-authToken~true} #account auth token - SECRET!!
      fromNumber: ${ssm:bulksms-fromNumber~true} #service id
    events:
      - http:
          method: post
          path: sendsms
          cors:
            origin: '*'
